### ISSUE TITLE
Impossible to use loggerPlugin

### ISSUE THREAD

**Issue by alexisab** [router5/router5#178]
Hi,

I try to use the loggerPlugin available in router5. Here is my code : 
```
const router = createRouter(routes)
if (config.env.NODE_ENV === 'development') {
        router.usePlugin(require('router5/plugins/logger'))
}
```

This code results in an error
```
TypeError: factoryFunction.apply is not a function
   at Object.executeFactory (/usr/src/client/node_modules/router5/create-router.js:278:32)
   at startPlugin (/usr/src/client/node_modules/router5/core/plugins.js:57:36)
   at addPlugin (/usr/src/client/node_modules/router5/core/plugins.js:41:13)
   at Array.forEach (native)
   at Object.usePlugin (/usr/src/client/node_modules/router5/core/plugins.js:34:17)
   at Object.create (/usr/src/client/src/services/router/index.js:34:16)
   at renderLandingPage (/usr/src/client-server/src/render.js:57:27)
   at Object.renderLogin (/usr/src/client-server/src/render.js:79:12)
   at _callee3$ (/usr/src/client-server/src/index.js:72:23)
   at tryCatch (/usr/src/client-server/node_modules/regenerator-runtime/runtime.js:64:40)
```

I've read the sources and the `apply` function is not defined in the loggerPlugin.
Maybe I've made a mistake or it's really a bug ?

**Comment by troch** [comment]
Change `require('router5/plugins/logger')` to `require('router5/plugins/logger').default`
